#!/bin/bash
#
# This file is part of Hawaii.
#
# Copyright (C) 2015 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

master=$1
nslave=$2

if [ -z "$master" -o -z "$nslave" ]; then
    echo "Usage: $0 <master> <nslave>"
    echo
    echo "Example: $0 localhost:9989 1"
    exit 1
fi

if [ "$(whoami)" != "root" ]; then
    echo "You must run $0 as root"
    exit 1
fi

set -x

name=x86_64-fedora-$(printf "%02d\n" $nslave)
path="/srv/buildbot/$name"
run="systemd-nspawn -D $path"

# Create the container
pkgs="systemd passwd dnf fedora-release vim-minimal make gcc git sudo python-devel python-pip rsync mock rpm-build livecd-tools appliance-tools fedora-kickstarts spin-kickstarts"
mkdir -p $path 
dnf -y --releasever=22 --nogpg --installroot=$path --disablerepo="*" --enablerepo=fedora install $pkgs || exit $?

# Password
$run bash -c "echo root:password | chpasswd" || exit $?

# Install Python modules
$run pip install --upgrade pip || exit $?
$run pip install mock pyaml networkx twisted || exit $?

# Install buildbot
$run rm -fr /srv/buildbot || exit $?
$run mkdir -p /srv/buildbot || exit $?
$run git clone --depth 1 https://github.com/buildbot/buildbot /srv/buildbot/src || exit $?
$run bash -c 'cd /srv/buildbot/src/slave; python setup.py install' || exit $?

# Create buildbot configuration
$run bash -c "cd /srv/buildbot; buildslave create-slave slave $master $name password" || exit $?

# systemd unit
cat >$path/etc/systemd/system/buildslave.service <<EOF
[Unit]
Description=Buildbot Slave
Wants=network.target
After=network.target

[Service]
Type=forking
PIDFile=/srv/buildbot/slave/twistd.pid
WorkingDirectory=/srv/buildbot
ExecStart=/usr/bin/buildslave start slave
ExecReload=/usr/bin/buildslave restart slave
ExecStop=/usr/bin/buildslave stop slave
Restart=always

[Install]
WantedBy=multi-user.target
EOF
$run ln -sf /etc/systemd/system/buildslave.service /etc/systemd/system/multi-user.target.wants/buildslave.service
