#!/bin/bash
#
# This file is part of Hawaii.
#
# Copyright (C) 2015 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Log into container  (username: admin   password: admin)
# ssh -p $(docker port $CONTAINER_ID 22 | cut -d: -f 2) admin@localhost

image=$1
admin=$2
host=$3

if [ -z "$image" -o -z "$admin" -o -z "$host" ]; then
    echo "Usage: $0 <image id> <admin> <host>"
    echo
    echo "Example: $0 x86_64-fedora-01 'Some Guy <some@guy.com>' 'Fedora x86_64 Container #1'"
    exit 1
fi

echo $admin | sudo docker run -i $image /bin/bash -c "cat >/data/buildbot/slave/info/admin"
echo $host | sudo docker run -i $image /bin/bash -c "cat >/data/buildbot/slave/info/host"
