#!/bin/bash
#
# This file is part of Hawaii.
#
# Copyright (C) 2015 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# Author(s):
#    Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# $BEGIN_LICENSE:GPL3$
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 3 (with exceptions) or any
# later version accepted by Pier Luigi Fiorini, which shall act as a
# proxy defined in Section 14 of version 3 of the license.
#
# Exceptions are described in Hawaii GPL Exception version 1.0,
# included in the file GPL3_EXCEPTION.txt in this package.
#
# Any modifications to this file must keep this entire header intact.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# $END_LICENSE$
#

image=$1
admin=$2
host=$3

if [ -z "$image" -o -z "$admin" -o -z "$host" ]; then
    echo "Usage: $0 <image id> <admin> <host>"
    echo
    echo "Example: $0 x86_64-fedora-01 'Some Guy <some@guy.com>' 'Fedora x86_64 Container #1'"
    exit 1
fi

echo $admin | sudo docker run -i $image /bin/bash -c "cat >/data/buildbot/slave/info/admin"
echo $host | sudo docker run -i $image /bin/bash -c "cat >/data/buildbot/slave/info/host"
