#!/bin/bash
#
# This file is part of Hawaii.
#
# Copyright (C) 2015 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Log into container  (username: admin   password: admin)
# ssh -p $(docker port $CONTAINER_ID 22 | cut -d: -f 2) admin@localhost

master=$1
nslave=$2

if [ -z "$master" -o -z "$nslave" ]; then
    echo "Usage: $0 <master> <nslave>"
    echo
    echo "Example: $0 localhost:9989 1"
    exit 1
fi

name=x86_64-archlinux-$(printf "%02d\n" $nslave)

if [ -f /etc/fedora-release ]; then
    sudo dnf install -y docker
else
    sudo pacman -S --noconfirm docker
fi
sudo systemctl start docker
sudo systemctl enable docker
cat Dockerfile | sed -e "s/@MASTER@/$master/g" -e "s/@SLAVE@/$name/g" | sudo docker build -t $name -
CONTAINER_ID=$(sudo docker run -d -p 22 $name)

sudo docker commit $CONTAINER_ID $name

echo "buildbot slave container: $CONTAINER_ID"
