#!/bin/bash
#
# This file is part of Hawaii.
#
# Copyright (C) 2015 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

pkgname=$1

if [ -z "$pkgname" ]; then
    echo "Usage: $0 <package name>"
    exit 1
fi

#
# Under the cwd (sources/$PKGNAME) we have a couple of directories:
#  - $PKGNAME: upstream sources
#  - downstream: RPM packaging stuff
#

# Copy the packaging directory
cp -R downstream work

# Compress sources
tar czf work/${pkgname}.tar.gz $pkgname

# Prepare spec file
pushd $pkgname
build_date=$(date +"%Y%m%d")
gitdate=$(git log -1 --format="%cd" --date=short | tr -d '-')
gitver=$(git log -1 --format="%h")
popd
cat downstream/${pkgname}.spec | sed -e "s,@BUILD_DATE@,$build_date," -e "s,@GIT_DATE@,$gitdate,g" -e "s,@GIT_VERSION@,$gitver," > work/${pkgname}.spec
