#!/bin/bash
#
# This file is part of Hawaii.
#
# Copyright (C) 2015 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

evr1=$1
evr2=$2

if [ -z "$evr1" -o -z "$evr2" ]; then
    echo "Usage: $0 <EVR1> <EVR2>"
    exit 1
fi

# Compare EVR1 with EVR2, we assume EVR1 is from the spec file and EVR2
# is from the last build
/usr/bin/rpmdev-vercmp $evr1 $evr2 2>&1 >/dev/null

# Return a string saying "yes" or "no", return "yes" when
# EVR1 is greater than EVR2
if [ $? -eq 11 ]; then
    echo "yes"
else
    echo "no"
fi
