#!/bin/bash
#
# This file is part of Hawaii.
#
# Copyright (C) 2015 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

spec=$1

if [ -z "$spec" ]; then
    echo "Usage: $0 <spec file>"
    exit 1
fi

if [ ! -f $spec ]; then
    echo "Spec file \"$spec\" not found!"
    exit 1
fi

name=$(/usr/bin/rpmspec -q --srpm --qf "%{name}\n" $spec | sed -e 's,^(none)$,,g')
epoch=$(/usr/bin/rpmspec -q --srpm --qf "%{epoch}\n" $spec)
version=$(/usr/bin/rpmspec -q --srpm --qf "%{version}\n" $spec | sed -e 's,^(none)$,,g')
release=$(/usr/bin/rpmspec -q --srpm --qf "%{release}\n" $spec | sed -e 's,^(none)$,,g')

if [ -z "$name" -o -z "$version" -o -z "$release" ]; then
    echo "Unable to retrieve NVR from \"$spec\""
    exit 1
fi

echo "${name} ${epoch} ${version} ${release}"
