#!/bin/bash
#
# This file is part of Hawaii.
#
# Copyright (C) 2015 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

basechrootdir=$1

if [ -z "$basechrootdir" ]; then
    echo "Usage: $0 <base chroot path>"
    exit 1
fi

basechrootdir=$(readlink -f $basechrootdir)

mkdir -p ~/.config
cat > ~/.config/clean-chroot-manager.conf <<EOF
CHROOTPATH64=${basechrootdir}64
CHROOTPATH32=${basechrootdir}32
THREADS=5
CFLAGS=""
RUNNAMCAP=
EOF
